language: go

matrix:
  fast_finish: true
  include:
  - go: 1.12.x
    env: GO111MODULE=on
  - go: master
    env: GO111MODULE=on

before_install:
  - if [[ "${GO111MODULE}" = "on" ]]; then mkdir "${HOME}/go"; export GOPATH="${HOME}/go"; fi

install:
  - if [[ "${GO111MODULE}" = "on" ]]; then go mod download; else make install; fi
  - if [[ "${GO111MODULE}" = "on" ]]; then export PATH="${GOPATH}/bin:${GOROOT}/bin:${PATH}"; fi

script:
  - make vet
  - make fmt_check
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash)
