// Autogenerated by Thrift Compiler (0.9.2)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package trace

import (
	"bytes"
	"fmt"
	"git.apache.org/thrift.git/lib/go/thrift"
)

// (needed to ensure safety because of naive import list construction.)
var _ = thrift.ZERO
var _ = fmt.Printf
var _ = bytes.Equal

var GoUnusedProtection__ int

type Trace struct {
	Id  string `thrift:"Id,1,required" json:"Id"`
	Pid string `thrift:"Pid,2,required" json:"Pid"`
	Cid string `thrift:"Cid,3,required" json:"Cid"`
}

func NewTrace() *Trace {
	return &Trace{}
}

func (p *Trace) GetId() string {
	return p.Id
}

func (p *Trace) GetPid() string {
	return p.Pid
}

func (p *Trace) GetCid() string {
	return p.Cid
}
func (p *Trace) Read(iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(); err != nil {
		return fmt.Errorf("%T read error: %s", p, err)
	}
	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
		if err != nil {
			return fmt.Errorf("%T field %d read error: %s", p, fieldId, err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if err := p.ReadField1(iprot); err != nil {
				return err
			}
		case 2:
			if err := p.ReadField2(iprot); err != nil {
				return err
			}
		case 3:
			if err := p.ReadField3(iprot); err != nil {
				return err
			}
		default:
			if err := iprot.Skip(fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(); err != nil {
		return fmt.Errorf("%T read struct end error: %s", p, err)
	}
	return nil
}

func (p *Trace) ReadField1(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(); err != nil {
		return fmt.Errorf("error reading field 1: %s", err)
	} else {
		p.Id = v
	}
	return nil
}

func (p *Trace) ReadField2(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(); err != nil {
		return fmt.Errorf("error reading field 2: %s", err)
	} else {
		p.Pid = v
	}
	return nil
}

func (p *Trace) ReadField3(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(); err != nil {
		return fmt.Errorf("error reading field 3: %s", err)
	} else {
		p.Cid = v
	}
	return nil
}

func (p *Trace) Write(oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin("Trace"); err != nil {
		return fmt.Errorf("%T write struct begin error: %s", p, err)
	}
	if err := p.writeField1(oprot); err != nil {
		return err
	}
	if err := p.writeField2(oprot); err != nil {
		return err
	}
	if err := p.writeField3(oprot); err != nil {
		return err
	}
	if err := oprot.WriteFieldStop(); err != nil {
		return fmt.Errorf("write field stop error: %s", err)
	}
	if err := oprot.WriteStructEnd(); err != nil {
		return fmt.Errorf("write struct stop error: %s", err)
	}
	return nil
}

func (p *Trace) writeField1(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("Id", thrift.STRING, 1); err != nil {
		return fmt.Errorf("%T write field begin error 1:Id: %s", p, err)
	}
	if err := oprot.WriteString(string(p.Id)); err != nil {
		return fmt.Errorf("%T.Id (1) field write error: %s", p, err)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return fmt.Errorf("%T write field end error 1:Id: %s", p, err)
	}
	return err
}

func (p *Trace) writeField2(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("Pid", thrift.STRING, 2); err != nil {
		return fmt.Errorf("%T write field begin error 2:Pid: %s", p, err)
	}
	if err := oprot.WriteString(string(p.Pid)); err != nil {
		return fmt.Errorf("%T.Pid (2) field write error: %s", p, err)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return fmt.Errorf("%T write field end error 2:Pid: %s", p, err)
	}
	return err
}

func (p *Trace) writeField3(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("Cid", thrift.STRING, 3); err != nil {
		return fmt.Errorf("%T write field begin error 3:Cid: %s", p, err)
	}
	if err := oprot.WriteString(string(p.Cid)); err != nil {
		return fmt.Errorf("%T.Cid (3) field write error: %s", p, err)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return fmt.Errorf("%T write field end error 3:Cid: %s", p, err)
	}
	return err
}

func (p *Trace) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Trace(%+v)", *p)
}
